const os=require("os")
// console.log(os.freemem());
// console.log(os.cpus());
// console.log(os.arch());
// console.log(os.platform());
// console.log(os.type());
// console.log(os.uptime());
// console.log(os.hostname());
// console.log(os.version());
// console.log(os.release());